"""
Audit script: scan all USGS spreadsheets and report data completeness.

Outputs gg_audit_report.md -- a refreshable reference for future sessions.
Run with: python gg_audit.py
"""

import os
import re
import sys
import pandas as pd
from gg_loader import (
    USGS_DIR, HERE,
    find_unit_value_column, commodity_name_from_filename,
)

BENCHMARKS = [1900, 1929, 1950, 1970, 2000, 2020]


def audit_one_file(filepath):
    """Return an audit dict for one USGS spreadsheet, or None on failure."""
    name = commodity_name_from_filename(filepath)
    result = {"name": name, "file": os.path.basename(filepath)}

    # Try both header offsets (most files use skiprows=4, a few use 5).
    df = pd.read_excel(filepath, skiprows=4)
    if "Year" not in df.columns:
        df = pd.read_excel(filepath, skiprows=5)
    if "Year" not in df.columns:
        result["status"] = "no Year column"
        return result

    col = find_unit_value_column(df.columns)
    if col is None:
        result["status"] = "no unit value column"
        result["columns"] = [c for c in df.columns if not str(c).startswith("Unnamed")]
        return result

    result["status"] = "ok"
    result["unit_col"] = col

    years = pd.to_numeric(df["Year"], errors="coerce").dropna().astype(int)
    values = pd.to_numeric(df[col], errors="coerce")
    valid = years[values.notna()]

    result["year_min"] = int(years.min())
    result["year_max"] = int(years.max())
    result["total_rows"] = len(years)
    result["valid_rows"] = len(valid)
    result["missing_pct"] = round(100 * (1 - len(valid) / len(years)), 1)

    for y in BENCHMARKS:
        result[f"has_{y}"] = y in valid.values

    # Flag large gaps (>5 consecutive missing years within the range).
    if len(valid) > 1:
        gaps = sorted(valid.values)
        max_gap = max(b - a for a, b in zip(gaps, gaps[1:]))
        result["max_gap"] = max_gap
    else:
        result["max_gap"] = 0

    return result


def write_report(audits, outpath):
    """Write the audit report as markdown."""
    ok = [a for a in audits if a["status"] == "ok"]
    excluded = [a for a in audits if a["status"] != "ok"]

    lines = []
    lines.append("# USGS Commodity Data Audit Report\n")
    lines.append(f"Generated by `gg_audit.py`. {len(ok)} loadable, "
                 f"{len(excluded)} excluded, {len(audits)} total files.\n")

    # Summary table.
    lines.append("## Loadable commodities\n")
    header = ("| Commodity | Years | Valid rows | Missing% | Max gap | "
              + " | ".join(str(y) for y in BENCHMARKS) + " |")
    sep = "|" + "|".join(["---"] * (7 + len(BENCHMARKS))) + "|"
    lines.append(header)
    lines.append(sep)

    for a in sorted(ok, key=lambda x: x["name"]):
        checks = " | ".join(
            "Y" if a.get(f"has_{y}") else "-" for y in BENCHMARKS
        )
        flag = " **gap**" if a["max_gap"] > 5 else ""
        lines.append(
            f"| {a['name']} | {a['year_min']}-{a['year_max']} "
            f"| {a['valid_rows']}/{a['total_rows']} "
            f"| {a['missing_pct']}% | {a['max_gap']}{flag} "
            f"| {checks} |"
        )

    # Excluded files.
    lines.append("\n## Excluded files\n")
    lines.append("| File | Reason | Available columns |")
    lines.append("|---|---|---|")
    for a in sorted(excluded, key=lambda x: x["name"]):
        cols = ", ".join(a.get("columns", []))
        lines.append(f"| {a['file']} | {a['status']} | {cols} |")

    # Decade histogram: how many commodities have data per decade.
    lines.append("\n## Coverage by decade\n")
    lines.append("How many commodities have at least one valid price per decade.\n")
    lines.append("| Decade | Count |")
    lines.append("|---|---|")
    for decade_start in range(1900, 2030, 10):
        count = sum(
            1 for a in ok
            if a["year_min"] <= decade_start + 9 and a["year_max"] >= decade_start
        )
        lines.append(f"| {decade_start}s | {count} |")

    with open(outpath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    print("Scanning USGS files...", file=sys.stderr)
    files = sorted(
        os.path.join(USGS_DIR, f)
        for f in os.listdir(USGS_DIR)
        if f.endswith(".xlsx") and " (" not in f
    )
    audits = [audit_one_file(f) for f in files]
    outpath = os.path.join(HERE, "gg_audit_report.md")
    write_report(audits, outpath)
    ok_count = sum(1 for a in audits if a["status"] == "ok")
    print(f"Done. {ok_count}/{len(audits)} loadable. Report: {outpath}",
          file=sys.stderr)
